var_1: &node_8_image circleci/node:8
var_2: &node_10_image circleci/node:10

version: 2
jobs:
  benchmark-node-8:
    docker:
      - image: *node_8_image
    steps:
      - checkout
      - run: ./runner.sh

  benchmark-node-10:
    docker:
      - image: *node_10_image
    steps:
      - checkout
      - run: ./runner.sh

workflows:
  version: 2
  default_workflow:
    jobs:
      - benchmark-node-10
      - benchmark-node-8